version: '3'

services:
  app:
    build: .
    container_name: school-calendar-app
    restart: always
    ports:
      - "${APP_PORT:-3501}:${APP_PORT:-3501}"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./credentials:/app/credentials
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app/main.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
